# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9cc6c4f53b63a04043e0b77c61327353481ea93060ca66b43275477f20e9008a7a0c1dcc65f7c3f3b4c5acec883c77e8d32d9557d45a2c027760c8339f1d790

test:
  secret_key_base: 140f7012ef3135a31568421444b84896f1007503202ec0e6d728f4bbdd6abce706582789c8fb047337c19ba11ea105d873d059e74af9367067d99d3a7989d0c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
